[package]
name = "bitcoinsuite-error"
version = "0.1.0"
authors = ["Tobias Ruck <ruck.tobias@gmail.com>"]
edition = "2021"

[dependencies]
bitcoinsuite-error-derive = { path = "../bitcoinsuite-error-derive" }
eyre = "0.6"
