[package]
name = "bitcoinsuite-error-warp"
version = "0.1.0"
edition = "2018"

[dependencies]
# HTTP server
warp = "0.3"

# Error handling
bitcoinsuite-error = { path = "../bitcoinsuite-error" }

# Serialize HTTP errors
serde = { version = "1.0", features = ["derive"] }
